In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_file_path = "https://raw.githubusercontent.com/upflairs-pvt-ltd/1st_june_data_science/master/customer_satisfaction/cust_satisfaction.csv"
df = pd.read_csv(data_file_path)
# df['satisfaction'].value_counts()
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [ ]:
# to check for duplicates
df.duplicated().sum()

np.int64(172)

In [6]:
# to drop the duplicates
df.drop_duplicates(inplace=True) # here inplace=True is used to permanently delete the duplicates

In [5]:
df.duplicated().sum()

np.int64(0)

In [10]:
# to count the values of a particular features(columns)
df['Gender'].value_counts()

Gender
Female    52651
Male      51081
Name: count, dtype: int64

## One Hot Encoding through library

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder,OrdinalEncoder

In [6]:
one_hot_encoder = OneHotEncoder()

In [7]:
cat_col = df.select_dtypes(include="O")
num_col = df.select_dtypes(exclude="O")

In [8]:
cat_col = pd.get_dummies(cat_col, drop_first=True)

In [9]:
transform_df = one_hot_encoder.fit_transform(cat_col)

In [10]:
transform_df = transform_df.toarray()

In [11]:
list(one_hot_encoder.get_feature_names_out())

['Gender_Male_False',
 'Gender_Male_True',
 'Customer Type_disloyal Customer_False',
 'Customer Type_disloyal Customer_True',
 'Type of Travel_Personal Travel_False',
 'Type of Travel_Personal Travel_True',
 'Class_Eco_False',
 'Class_Eco_True',
 'Class_Eco Plus_False',
 'Class_Eco Plus_True',
 'satisfaction_satisfied_False',
 'satisfaction_satisfied_True']

In [12]:
transform_df.shape
pd.DataFrame(transform_df)

         0    1    2    3    4    5    6    7    8    9    10   11
0       0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0
1       0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
2       1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0
3       1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
4       0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
103417  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0
103418  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0
103419  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
103420  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0
103421  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0

[103422 rows x 12 columns]

In [13]:
pd.DataFrame(transform_df, columns=one_hot_encoder.get_feature_names_out())

,Gender_Male_False,Gender_Male_True,Customer Type_disloyal Customer_False,Customer Type_disloyal Customer_True,Type of Travel_Personal Travel_False,Type of Travel_Personal Travel_True,Class_Eco_False,Class_Eco_True,Class_Eco Plus_False,Class_Eco Plus_True,satisfaction_satisfied_False,satisfaction_satisfied_True
0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
1,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
3,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
4,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103417,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
103418,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
103419,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
103420,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
103421,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

## One Hot Encoding through Pandas

In [14]:
cat_col = df.select_dtypes(include="O")
num_col = df.select_dtypes(exclude="O")

In [15]:
cat_col.head()

,Gender,Customer Type,Type of Travel,Class,satisfaction
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied
2,Female,Loyal Customer,Business travel,Business,satisfied
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied
4,Male,Loyal Customer,Business travel,Business,satisfied

In [16]:
pd_encoded_data = pd.get_dummies(cat_col, drop_first=True).astype(int)

In [17]:
complete_df = pd.concat([pd_encoded_data, num_col], axis=1)
complete_df.head()

,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Eco,Class_Eco Plus,satisfaction_satisfied,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1,0,1,0,1,0,13,460,5,4,5,25,18.0
1,1,1,0,0,0,0,25,235,1,3,1,1,6.0
2,0,0,0,0,0,1,26,1142,5,4,5,0,0.0
3,0,0,0,0,0,0,25,562,2,3,2,11,9.0
4,1,0,0,0,0,1,61,214,3,4,3,0,0.0

In [18]:
complete_df.dtypes

Gender_Male                          int64
Customer Type_disloyal Customer      int64
Type of Travel_Personal Travel       int64
Class_Eco                            int64
Class_Eco Plus                       int64
satisfaction_satisfied               int64
Age                                  int64
Flight Distance                      int64
Inflight entertainment               int64
Baggage handling                     int64
Cleanliness                          int64
Departure Delay in Minutes           int64
Arrival Delay in Minutes           float64
dtype: object

In [19]:
# Data Splitting

x = complete_df.drop("satisfaction_satisfied", axis=1)
x.head()
x['Flight Distance'].max()

np.int64(4983)

In [20]:
y = complete_df[["satisfaction_satisfied"]]
y.head()
y.shape

(103422, 1)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [33]:
x_train.columns

Index(['Gender_Male', 'Customer Type_disloyal Customer',
       'Type of Travel_Personal Travel', 'Class_Eco', 'Class_Eco Plus', 'Age',
       'Flight Distance', 'Inflight entertainment', 'Baggage handling',
       'Cleanliness', 'Departure Delay in Minutes',
       'Arrival Delay in Minutes'],
      dtype='object')

In [23]:
# Model Selection
from sklearn.linear_model import LogisticRegression

In [24]:
lgr = LogisticRegression(max_iter=1000)

In [25]:
# Model Training

lgr.fit(x_train, y_train)

c:\Users\bhart\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\bhart\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [26]:
# Model Testing

y_pred = lgr.predict(x_test)
score = lgr.score(x_test, y_test)
score

0.8348078317621465

In [27]:
y_train.shape

(82737, 1)

In [28]:
from sklearn.metrics import confusion_matrix, classification_report

In [29]:
# y_test ==> actual values
# y_pred ==> predicted values
matrix = confusion_matrix(y_test, y_pred)
matrix

array([[10121,  1664],
       [ 1753,  7147]])

In [30]:
y_test['predicted'] = y_pred

In [31]:
y_test.head()

       satisfaction_satisfied  predicted
40794                       1          1
28574                       1          1
4920                        0          0
71169                       1          1
67168                       1          1

In [32]:
y_test.shape

(20685, 2)